USE QLDA;
GO

-- 1. Mỗi đề án: Tên đề án + tổng số giờ
-- DECIMAL(10,2) - CAST
SELECT DA.TENDEAN,
       CAST(SUM(PC.THOIGIAN) AS DECIMAL(10,2)) AS TongGio
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;

-- DECIMAL(10,2) - CONVERT
SELECT DA.TENDEAN,
       CONVERT(DECIMAL(10,2), SUM(PC.THOIGIAN)) AS TongGio
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;

-- VARCHAR - CAST
SELECT DA.TENDEAN,
       CAST(SUM(PC.THOIGIAN) AS VARCHAR(20)) AS TongGio
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;

-- VARCHAR - CONVERT
SELECT DA.TENDEAN,
       CONVERT(VARCHAR(20), SUM(PC.THOIGIAN)) AS TongGio
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;


-- 2. Phòng ban: tên + lương TB
-- DECIMAL(10,2) - CAST
SELECT PB.TENPHG,
       CAST(AVG(NV.LUONG) AS DECIMAL(10,2)) AS LuongTB
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY PB.TENPHG;

-- DECIMAL(10,2) - CONVERT
SELECT PB.TENPHG,
       CONVERT(DECIMAL(10,2), AVG(NV.LUONG)) AS LuongTB
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY PB.TENPHG;

-- VARCHAR có dấu phẩy mỗi 3 số
SELECT PB.TENPHG,
       REPLACE(CONVERT(VARCHAR, CAST(AVG(NV.LUONG) AS MONEY), 1), '.00','') AS LuongTB_VARCHAR
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY PB.TENPHG;


----bài 2----
-- 1. Tổng số giờ / đề án
SELECT DA.TENDEAN, CEILING(SUM(PC.THOIGIAN)) AS TongGio_CEILING
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;

SELECT DA.TENDEAN, FLOOR(SUM(PC.THOIGIAN)) AS TongGio_FLOOR
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;

SELECT DA.TENDEAN, ROUND(SUM(PC.THOIGIAN),2) AS TongGio_ROUND
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;


-- 2. Nhân viên có lương > lương TB phòng "Nghiên cứu"
SELECT NV.HONV, NV.TENLOT, NV.TENNV, NV.LUONG
FROM NHANVIEN NV
WHERE NV.LUONG > (
    SELECT ROUND(AVG(N.LUONG),2)
    FROM NHANVIEN N
    JOIN PHONGBAN P ON N.PHG = P.MAPHG
    WHERE P.TENPHG = N'Nghiên cứu'
);

---- bài 3----
-- 1. Danh sách nhân viên có trên 2 thân nhân
SELECT 
    UPPER(NV.HONV) AS HoNV,                     
    LOWER(NV.TENLOT) AS TenLot,                  

    -- xử lý TENNV: ký tự đầu thường + ký tự thứ 2 hoa + phần còn lại thường
    LOWER(LEFT(NV.TENNV,1)) 
        + UPPER(SUBSTRING(NV.TENNV,2,1)) 
        + LOWER(SUBSTRING(NV.TENNV,3,LEN(NV.TENNV))) AS TenNV,

    -- chỉ lấy phần tên đường (giữa số nhà và dấu phẩy đầu tiên)
    SUBSTRING(
        NV.DCHI,
        CHARINDEX(' ', NV.DCHI) + 1,
        CHARINDEX(',', NV.DCHI) - CHARINDEX(' ', NV.DCHI) - 1
    ) AS DiaChi

FROM NHANVIEN NV
WHERE (SELECT COUNT(*) FROM THANNHAN TN WHERE TN.MA_NVIEN = NV.MANV) > 2;



-- 2. Phòng ban có đông nhân viên nhất, thêm cột thay tên trưởng phòng = 'Fpoly'
SELECT TOP 1 
       PB.TENPHG,
       NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV AS TruongPhong,
       'Fpoly' AS TenThayThe
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.TRPHG = NV.MANV
ORDER BY (SELECT COUNT(*) FROM NHANVIEN N WHERE N.PHG = PB.MAPHG) DESC;


-----bài 4-----
-- 1. Nhân viên sinh trong giai đoạn 1960-1965
SELECT *
FROM NHANVIEN
WHERE YEAR(NGSINH) BETWEEN 1960 AND 1965;

-- 2. Tính tuổi nhân viên đến hiện tại
SELECT HONV, TENLOT, TENNV,
       DATEDIFF(YEAR, NGSINH, GETDATE()) AS Tuoi
FROM NHANVIEN;

-- 3. Cho biết nhân viên sinh vào thứ mấy
SELECT HONV, TENLOT, TENNV,
       DATENAME(WEEKDAY, NGSINH) AS ThuSinh
FROM NHANVIEN;

-- 4. Số lượng nhân viên, tên trưởng phòng, ngày nhận chức (dd-mm-yy)
SELECT COUNT(NV.MANV) AS SoLuongNV,
       TP.HONV + ' ' + TP.TENLOT + ' ' + TP.TENNV AS TruongPhong,
       CONVERT(VARCHAR(10), PB.NG_NHANCHUC, 105) AS NgayNhanChuc
FROM PHONGBAN PB
JOIN NHANVIEN TP ON PB.TRPHG = TP.MANV
JOIN NHANVIEN NV ON NV.PHG = PB.MAPHG
GROUP BY TP.HONV, TP.TENLOT, TP.TENNV, PB.NG_NHANCHUC;
